// demos/vue/ckeditor5/src/App.vue
<template>
  <div id="app">
    <ckeditor :editor="editor" v-model="editorData" :config="editorConfig" @ready="onEditorReady"></ckeditor>
  </div>
</template>

<script lang="ts">
import { ClassicEditor, Essentials, Paragraph, Bold, Italic, Link, SourceEditing } from "ckeditor5";
import "ckeditor5/ckeditor5.css";

// @ts-ignore
import MathType from "@wiris/mathtype-ckeditor5/dist/index.js";

// @ts-ignore
// Import the wiris plugin version.
import { version as pluginVersion } from "@wiris/mathtype-ckeditor5/package.json";

// @ts-ignore
// Load the file that contains common imports between demos. (functions, styles, etc)
import * as Generic from "resources/demos/vite-imports";

// Apply specific demo names to all the objects.
document.getElementById("header_title_name")!.innerHTML = "MathType for CKEditor 5 on Vue";
document.getElementById("version_editor")!.innerHTML = "CKEditor editor: ";

// Get and set the editor and wiris versions in this order.
Generic.setEditorAndWirisVersion("5.0.0", pluginVersion);

// Get the initial content.
const content = Generic.editorContentMathML;

const toolbar = ["bold", "italic", "link", "undo", "redo", "MathType", "ChemType", "sourceEditing"];
const plugins = [Essentials, Bold, Italic, Link, Paragraph, MathType, SourceEditing];
const editorConfig = {
  iframe: true,
  charCounterCount: false,
  plugins,
  toolbar,
  htmlAllowedTags: [".*"],
  htmlAllowedAttrs: [".*"],
  htmlAllowedEmptyTags: ["mprescripts"],
  imageResize: false,
  useClasses: false,
};

// Function to call when the editor is initialyzed so it can add listeners on buttons.
function updateContent(ckeditor: ClassicEditor) {
  // Set the initial content on the bottom textArea.
  document.getElementById("transform_content")!.innerHTML = content;

  // Add listener on click button to launch updateContent function.
  document.getElementById("btn_update")!.addEventListener("click", (e) => {
    e.preventDefault();
    Generic.updateContent(ckeditor.getData(), "transform_content");
  });
}

export default {
  name: "#editor",
  data() {
    return {
      editor: ClassicEditor as {
        create: any;
      },
      editorData: content,
      editorConfig,
      onEditorReady: updateContent,
    };
  },
};
</script>

// demos/angular/ckeditor5/src/app/app.component.ts
import { Component } from '@angular/core';

import * as ClassicEditor from '../ckeditor';

// Import common resources.
import * as Generic from 'resources/demos/angular-imports';

// Load wiris plugin version.
import { version as pluginVersion } from '@wiris/mathtype-ckeditor5/package.json';

// Apply specific demo names to all the objects.
document.getElementById('header_title_name').innerHTML = 'Mathtype for CKeditor';
document.getElementById('version_editor').innerHTML = 'CKeditor editor: ';

// Create the initial editor content.
const editorContent = '<p class="text"> Double click on the following formula to edit it.</p><p style="text-align:center;"><math><mi>z</mi><mo>=</mo><mfrac><mrow><mo>-</mo><mi>b</mi><mo>&PlusMinus;</mo><msqrt><msup><mi>b</mi><mn>3</mn></msup><mo>-</mo><mn>4</mn><mi>a</mi><mi>c</mi></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></math></p>';

// Copy the editor content before initializing it.
document.getElementById('transform_content').innerHTML = editorContent;

// Add listener on click button to launch updateContent function.
document.getElementById('btn_update').addEventListener('click', () => {
  Generic.updateContent(ClassicEditor.getData(), 'transform_content');
});

@Component({
  selector: '#editor',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  public Editor = ClassicEditor;

  // Initializate the editors content.
  public content: string = editorContent;
  
  public options: Object = {
    toolbar: [ 'heading', '|', 'bold', 'italic', 'MathType', 'ChemType' ],
    htmlAllowedTags:  ['.*'],
    htmlAllowedAttrs: ['.*'],
  }
  
  title = 'ckeditor5';
}

// Get and set the editor and wiris versions in this order.
Generic.setEditorAndWirisVersion('5.0.0', pluginVersion);
<ckeditor [config]="options" [editor]="Editor" [data]="content"></ckeditor>
